version: '3'
services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_network
    container_name: postgres

  backend:
    build:
      context: ./music-map-express
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./music-map-express:/app/backend
    depends_on:
      - postgres
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      DB_HOST: postgres
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - my_network
    container_name: backend

  frontend:
    build:
      context: ./music-map-react
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./music-map-react:/app/frontend
    environment:
      FRONTEND_PORT: ${FRONTEND_PORT}
      BACKEND_PORT: ${BACKEND_PORT}
      REACT_APP_GOOGLE_MAPS_API_KEY: ${REACT_APP_GOOGLE_MAPS_API_KEY}
    networks:
      - my_network
    container_name: frontend


volumes:
  postgres-data:

networks:
  my_network:
    driver: bridge